/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SubMenu.Popup.Laporan;

import SubMenu.Popup.PopupSukses;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import koneksi.Connect;

/**
 *
 * @author alans
 */
public class YakinHapus extends javax.swing.JFrame {

    String tanggal_pengeluaran;
    String tanggal_input;
    JDesktopPane pane;

    /**
     * Creates new form YakinHapus
     */
    public YakinHapus() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
    }

    public YakinHapus(String pesan, String tgl_pengeluaran, String tgl_input, JDesktopPane pane) {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        lbl_pesan.setText("<html><center>" + pesan + "</center></html>");
        this.tanggal_pengeluaran = tgl_pengeluaran;
        this.tanggal_input = tgl_input;
        this.pane = pane;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        batal_button = new utility.custom_panel.PanelRound();
        oke_button = new utility.custom_panel.PanelRound();
        lbl_pesan = new javax.swing.JLabel();
        backgorund = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        batal_button.setBackground(new Color(0,0,0,0));
        batal_button.setRoundBottomLeft(10);
        batal_button.setRoundBottomRight(10);
        batal_button.setRoundTopLeft(10);
        batal_button.setRoundTopRight(10);
        batal_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                batal_buttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout batal_buttonLayout = new javax.swing.GroupLayout(batal_button);
        batal_button.setLayout(batal_buttonLayout);
        batal_buttonLayout.setHorizontalGroup(
            batal_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );
        batal_buttonLayout.setVerticalGroup(
            batal_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(batal_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, 186, 40));

        oke_button.setBackground(new Color(0,0,0,0));
        oke_button.setRoundBottomLeft(10);
        oke_button.setRoundBottomRight(10);
        oke_button.setRoundTopLeft(10);
        oke_button.setRoundTopRight(10);
        oke_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oke_buttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout oke_buttonLayout = new javax.swing.GroupLayout(oke_button);
        oke_button.setLayout(oke_buttonLayout);
        oke_buttonLayout.setHorizontalGroup(
            oke_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );
        oke_buttonLayout.setVerticalGroup(
            oke_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(oke_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, 186, 40));

        lbl_pesan.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        lbl_pesan.setForeground(new java.awt.Color(0, 0, 0));
        lbl_pesan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_pesan.setText("Title Here");
        getContentPane().add(lbl_pesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 360, 500, 100));

        backgorund.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/PopUp/Template Pop up konfirmasi.png"))); // NOI18N
        getContentPane().add(backgorund, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1366, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void batal_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_batal_buttonMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_batal_buttonMouseClicked

    private void oke_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oke_buttonMouseClicked
        String tampilan = "yyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal = this.tanggal_pengeluaran;

        try {
            String searchId = "SELECT * FROM pengeluaran WHERE tanggal_input = '" + this.tanggal_input + "'";

            Connection conn = Connect.GetConnection();
            PreparedStatement pst = conn.prepareStatement(searchId);
            ResultSet res = pst.executeQuery();
            res.next();

            String sql = "DELETE FROM pengeluaran WHERE tanggal_input = '" + this.tanggal_input + "'";

            PreparedStatement pst2 = conn.prepareStatement(sql);
            pst2.executeUpdate(sql);

            new PopupSukses("Data berhasil dihapus", "laporanPengeluaran", pane).setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_oke_buttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YakinHapus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YakinHapus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YakinHapus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YakinHapus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YakinHapus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgorund;
    private utility.custom_panel.PanelRound batal_button;
    private javax.swing.JLabel lbl_pesan;
    private utility.custom_panel.PanelRound oke_button;
    // End of variables declaration//GEN-END:variables
}
