/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SubMenu.Popup.Pelanggan;

import SubMenu.PelangganFrame;
import SubMenu.Popup.PopupGagal;
import SubMenu.Popup.PopupSukses;
import java.awt.Color;
import java.sql.Connection;
import javax.swing.JDesktopPane;

/**
 *
 * @author gilan
 */
public class popup_konfirmHapus extends javax.swing.JFrame {

    String idPelanggan = "";
    JDesktopPane pane;

    /**
     * Creates new form popup_hapus
     */
    public popup_konfirmHapus(String pesan, String idPelanggan, JDesktopPane pane) {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        this.idPelanggan = idPelanggan;
        this.pane = pane;
        lbl_pesan.setText("<html><center>" + pesan + "</center></html>");
    }

    public popup_konfirmHapus() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_batal = new javax.swing.JLabel();
        btn_oke = new javax.swing.JLabel();
        lbl_pesan = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        btn_batal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_batal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_batalMouseClicked(evt);
            }
        });
        getContentPane().add(btn_batal);
        btn_batal.setBounds(471, 481, 187, 40);

        btn_oke.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_oke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_okeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_oke);
        btn_oke.setBounds(709, 481, 187, 40);

        lbl_pesan.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        lbl_pesan.setForeground(new java.awt.Color(0, 0, 0));
        lbl_pesan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_pesan.setText("Title Here");
        getContentPane().add(lbl_pesan);
        lbl_pesan.setBounds(432, 360, 500, 100);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/popup/Template Pop up konfirmasi.png"))); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, 0, 1366, 768);

        setSize(new java.awt.Dimension(1366, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_batalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_batalMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_batalMouseClicked

    private void btn_okeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_okeMouseClicked
        // TODO add your handling code here:
        PelangganFrame PF = new PelangganFrame();
        try {
            String resultSet = "DELETE FROM pelanggan WHERE id_pelanggan = '" + this.idPelanggan + "'";

            java.sql.Connection con = (Connection) koneksi.Connect.GetConnection();
            java.sql.PreparedStatement pst = con.prepareStatement(resultSet);
            pst.execute();

            PF.clear();
            PF.getData();
            PF.hapus = false;

            this.pane.add(PF);
            PF.setVisible(true);

            new PopupSukses("Data berhasil dihapus", "pelanggan", this.pane).setVisible(true);

        } catch (Exception e) {
            new PopupGagal("Data gagal dihapus\nsilahkan coba lagi").setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_btn_okeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(popup_konfirmHapus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(popup_konfirmHapus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(popup_konfirmHapus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(popup_konfirmHapus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new popup_konfirmHapus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btn_batal;
    private javax.swing.JLabel btn_oke;
    private javax.swing.JLabel lbl_pesan;
    // End of variables declaration//GEN-END:variables
}
