/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainMenu;

import javax.mail.PasswordAuthentication;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import java.sql.*;
import java.util.Random;
import koneksi.Connect;
import SubMenu.Popup.PopupGagalLogin;
import SubMenu.Popup.PopupSuksesLogin;
import java.awt.event.KeyEvent;

/**
 *
 * @author perlengkapan
 */
public class ForgetPassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgetPassword
     */
    public ForgetPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_close = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_username.setBackground(new java.awt.Color(217, 217, 217));
        txt_username.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        txt_username.setBorder(null);
        txt_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_usernameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_usernameKeyReleased(evt);
            }
        });
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 310, 40));

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 360, 50));

        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/icon/close login.png"))); // NOI18N
        btn_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1235, 16, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/icon/back login.png"))); // NOI18N
        jLabel2.setText("Kembali");
        jLabel2.setToolTipText("");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 169, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/layout/Forget Password Page.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        String ToEmail = "";
        String FromEmail = "otpstayclean@gmail.com";
        String FromEmailPassword = "fefybsmxlxeefimy";
        String Subjects = "Kode Verifikasi Stay Clean";

        Properties properties = new Properties();
        properties.put("mail.smtp.auth", "true");
        properties.put("mail.smtp.starttls.enable", "true");
        properties.put("mail.smtp.host", "smtp.gmail.com");
        properties.put("mail.smtp.port", "587");

        Session session = Session.getDefaultInstance(properties, new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(FromEmail, FromEmailPassword);
            }
        });

        try {
            //ambil data nama dari database berdasarkan email yang dimasukkan
            Connection conn = Connect.GetConnection();
            String sql = "Select * from akun where username = '" + txt_username.getText() + "' or email = '" + txt_username.getText() + "'";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet res = pst.executeQuery();
            res.next();
            ToEmail = res.getString("email");
            String id_akun = res.getString("id_akun");

            //generate kode
            Random random = new Random();
            int number = random.nextInt(99999);

            //mengirim pesan email
            MimeMessage message = new MimeMessage(session);
            message.setFrom(new InternetAddress(FromEmail, "Stay Clean OTP"));
            message.addRecipient(Message.RecipientType.TO, new InternetAddress(ToEmail));
            message.setSubject(Subjects);
            message.setText("Kepada " + res.getString("nama") + ",\n"
                    + "\n"
                    + "Untuk menyelesaikan proses reset password, kami memerlukan verifikasi email Anda dengan memasukkan kode verifikasi berikut:\n"
                    + "\n"
                    + "Kode Verifikasi anda : " + number + "\n"
                    + "\n"
                    + "Silakan masukkan kode ini pada halaman verifikasi email. Jika Anda tidak melakukan pengaturan ulang password pada aplikasi Stay Clean, mohon abaikan email ini dan jangan berikan kode verifikasi ini pada pihak manapun.\n"
                    + "\n"
                    + "Kami mohon untuk tidak memberikan kode verifikasi ini pada orang lain untuk menjaga keamanan akun Anda. Jangan ragu untuk menghubungi kami jika Anda mengalami kesulitan atau memiliki pertanyaan lebih lanjut.\n"
                    + "\n"
                    + "Terima kasih atas perhatiannya.\n"
                    + "\n"
                    + "Salam Hormat, Stay Clean");
            Transport.send(message);

            this.dispose();
            Verification v = new Verification();
            v.getVerif(number, id_akun);
            v.setVisible(true);
            new PopupSuksesLogin("Kode OTP telah terkirim<br>Silahkan cek email anda", "").setVisible(true);

        } catch (Exception e) {
            new PopupGagalLogin("Silahkan cek kembali username atau email yang anda masukkan").setVisible(true);
            System.out.println(e.getMessage());
            txt_username.requestFocus();
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void txt_usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usernameKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            String idAkun = "";
            String ToEmail = "";
            String FromEmail = "otpstayclean@gmail.com";
            String FromEmailPassword = "fefybsmxlxeefimy";
            String Subjects = "Kode Verifikasi Stay Clean";

            Properties properties = new Properties();
            properties.put("mail.smtp.auth", "true");
            properties.put("mail.smtp.starttls.enable", "true");
            properties.put("mail.smtp.host", "smtp.gmail.com");
            properties.put("mail.smtp.port", "587");

            Session session = Session.getDefaultInstance(properties, new javax.mail.Authenticator() {
                protected PasswordAuthentication getPasswordAuthentication() {
                    return new PasswordAuthentication(FromEmail, FromEmailPassword);
                }
            });

            try {
                //ambil data nama dari database berdasarkan email yang dimasukkan
                Connection conn = Connect.GetConnection();
                String sql = "Select * from akun where username = '" + txt_username.getText() + "' or email = '" + txt_username.getText() + "'";
                PreparedStatement pst = conn.prepareStatement(sql);
                ResultSet res = pst.executeQuery();
                if (res.next()) {
                    ToEmail = res.getString("email");
                    idAkun = res.getString("id_akun");
                }

                //generate kode
                Random random = new Random();
                int number = random.nextInt(99999);

                //mengirim pesan email
                MimeMessage message = new MimeMessage(session);
                message.setFrom(new InternetAddress(FromEmail, "Stay Clean OTP"));
                message.addRecipient(Message.RecipientType.TO, new InternetAddress(ToEmail));
                message.setSubject(Subjects);
                message.setText("Kepada " + res.getString("nama") + ",\n"
                        + "\n"
                        + "Untuk menyelesaikan proses reset password, kami memerlukan verifikasi email Anda dengan memasukkan kode verifikasi berikut:\n"
                        + "\n"
                        + "Kode Verifikasi anda : " + number + "\n"
                        + "\n"
                        + "Silakan masukkan kode ini pada halaman verifikasi email. Jika Anda tidak melakukan pengaturan ulang password pada aplikasi Stay Clean, mohon abaikan email ini dan jangan berikan kode verifikasi ini pada pihak manapun.\n"
                        + "\n"
                        + "Kami mohon untuk tidak memberikan kode verifikasi ini pada orang lain untuk menjaga keamanan akun Anda. Jangan ragu untuk menghubungi kami jika Anda mengalami kesulitan atau memiliki pertanyaan lebih lanjut.\n"
                        + "\n"
                        + "Terima kasih atas perhatiannya.\n"
                        + "\n"
                        + "Salam Hormat, Stay Clean");
                Transport.send(message);

                this.dispose();
                Verification v = new Verification();
                v.getVerif(number, idAkun);
                v.setVisible(true);
                new PopupSuksesLogin("Kode OTP telah terkirim<br>Silahkan cek email anda", "").setVisible(true);

            } catch (Exception e) {
                new PopupGagalLogin("Silahkan cek kembali username atau email yang anda masukkan").setVisible(true);
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_txt_usernameKeyPressed

    private void txt_usernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usernameKeyReleased
        txt_username.setText(txt_username.getText().replaceAll("\\s+", ""));
        txt_username.setText(txt_username.getText().toLowerCase());
        txt_username.setText(txt_username.getText().replaceAll("[^a-z0-9.@]", ""));
    }//GEN-LAST:event_txt_usernameKeyReleased

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        new LoginPage().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btn_closeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgetPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel btn_close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
