/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainMenu;

import SubMenu.Popup.PopupGagalLogin;
import SubMenu.Popup.PopupSukses;
import koneksi.Connect;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author rayrayaray
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public LoginPage() {
        initComponents();

        iconEyeClose.setVisible(false);
        txt_password.setEchoChar('\u2022');
    }

    private void caseSensitive(JTextField textfield) {
        textfield.setText(textfield.getText().toLowerCase());
        textfield.setText(textfield.getText().replaceAll("\\s+", ""));
    }

    private void numberOnly(JTextField textfield) {
        textfield.setText(textfield.getText().replaceAll("[^0-9]", ""));
    }

    private void alphabetOnly(JTextField textfield) {
        textfield.setText(textfield.getText().replaceAll("[^a-z]", ""));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_username = new javax.swing.JTextField();
        btn_login = new javax.swing.JLabel();
        btn_lupaPass = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        iconEyeClose = new javax.swing.JLabel();
        iconEyeOpen = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        btn_close = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_username.setBackground(new java.awt.Color(217, 217, 217));
        txt_username.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        txt_username.setBorder(null);
        txt_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_usernameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_usernameKeyReleased(evt);
            }
        });
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 333, 300, 40));

        btn_login.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_loginMouseClicked(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 526, 310, 39));

        btn_lupaPass.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btn_lupaPass.setText("Lupa Password ?");
        btn_lupaPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_lupaPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_lupaPassMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_lupaPassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_lupaPassMouseExited(evt);
            }
        });
        getContentPane().add(btn_lupaPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, -1, 20));

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setOpaque(false);
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 525, 43, 40));

        iconEyeClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/icon/eye close.png"))); // NOI18N
        iconEyeClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconEyeClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconEyeCloseMouseClicked(evt);
            }
        });
        getContentPane().add(iconEyeClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 30, 40));

        iconEyeOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/icon/eye open.png"))); // NOI18N
        iconEyeOpen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconEyeOpen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconEyeOpenMouseClicked(evt);
            }
        });
        getContentPane().add(iconEyeOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 30, 40));

        txt_password.setBackground(new java.awt.Color(217, 217, 217));
        txt_password.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        txt_password.setBorder(null);
        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passwordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_passwordKeyReleased(evt);
            }
        });
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 270, 40));

        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/icon/close login.png"))); // NOI18N
        btn_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1235, 16, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/layout/Login Page.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseClicked
        String username = txt_username.getText();
        String password = txt_password.getText();

        if (txt_username.getText().equals("")) {
            new PopupGagalLogin("Silahkan isi nama pengguna terlebih dahulu").setVisible(true);
        } else if (txt_password.getText().equals("")) {
            new PopupGagalLogin("Silahkan isi kata sandi terlebih dahulu").setVisible(true);
        } else if (txt_password.getText().length() < 6) {
            new PopupGagalLogin("Kata sandi minimal 6 karakter").setVisible(true);
        } else {
            try {
                Connection conn = Connect.GetConnection();
                String sql = "SELECT * FROM akun WHERE username = '" + username + "' AND PASSWORD = '" + password + "'";
                PreparedStatement pst = conn.prepareStatement(sql);
                ResultSet res = pst.executeQuery(sql);

                if (res.next()) {
                    this.dispose();
                    MenuUtama mu = new MenuUtama();
                    System.out.println(res.getString("hak_akses"));
                    mu.getIdAkun(res.getString("id_akun"), res.getString("hak_akses"));
                    mu.setVisible(true);
                    mu.cekRole();
                    new PopupSukses("Berhasil Login<br>Selamat datang " + res.getString("nama"), "").setVisible(true);
                } else {
                    new PopupGagalLogin("Username atau Password salah<br>silahkan cek kembali!").setVisible(true);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error login");
                System.out.println(username);
                System.out.println(password);
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btn_loginMouseClicked

    private void btn_lupaPassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lupaPassMouseEntered
        btn_lupaPass.setForeground(new Color(0, 155, 182));
    }//GEN-LAST:event_btn_lupaPassMouseEntered

    private void btn_lupaPassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lupaPassMouseExited
        btn_lupaPass.setForeground(Color.black);
    }//GEN-LAST:event_btn_lupaPassMouseExited

    private void btn_lupaPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lupaPassMouseClicked
        new ForgetPassword().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_lupaPassMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        new LoginRFID().setVisible(true);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void txt_usernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usernameKeyReleased
        caseSensitive(txt_username);
        alphabetOnly(txt_username);
    }//GEN-LAST:event_txt_usernameKeyReleased

    private void iconEyeOpenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconEyeOpenMouseClicked
        iconEyeOpen.setVisible(false);
        iconEyeClose.setVisible(true);
        txt_password.setEchoChar((char) 0);

    }//GEN-LAST:event_iconEyeOpenMouseClicked

    private void txt_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String username = txt_username.getText();
            String password = txt_password.getText();

            if (txt_username.getText().equals("")) {
                new PopupGagalLogin("Silahkan isi nama pengguna terlebih dahulu").setVisible(true);
            } else if (txt_password.getText().equals("")) {
                new PopupGagalLogin("Silahkan isi kata sandi terlebih dahulu").setVisible(true);
            } else if (txt_password.getText().length() < 6) {
                new PopupGagalLogin("Kata sandi minimal 6 karakter").setVisible(true);
            } else {
                try {
                    Connection conn = Connect.GetConnection();
                    String sql = "SELECT * FROM akun WHERE username = '" + username + "' AND BINARY PASSWORD = '" + password + "'";
                    PreparedStatement pst = conn.prepareStatement(sql);
                    ResultSet res = pst.executeQuery(sql);

                    if (res.next()) {
                        this.dispose();
                        MenuUtama mu = new MenuUtama();
                        mu.getIdAkun(res.getString("id_akun"), res.getString("hak_akses"));
                        mu.setVisible(true);
                        mu.cekRole();
                        new PopupSukses("Berhasil Login<br>Selamat datang " + res.getString("nama"), "").setVisible(true);
                    } else {
                        new PopupGagalLogin("Username atau Password salah<br>silahkan cek kembali!").setVisible(true);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error login");
                    System.out.println(username);
                    System.out.println(password);
                    System.out.println(e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_txt_passwordKeyPressed

    private void iconEyeCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconEyeCloseMouseClicked
        iconEyeOpen.setVisible(true);
        iconEyeClose.setVisible(false);
        txt_password.setEchoChar('\u2022');
    }//GEN-LAST:event_iconEyeCloseMouseClicked

    private void txt_usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usernameKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            txt_password.requestFocus();
        }
    }//GEN-LAST:event_txt_usernameKeyPressed

    private void txt_passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyReleased
        txt_password.setText(txt_password.getText().replaceAll("\\s+", ""));
    }//GEN-LAST:event_txt_passwordKeyReleased

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btn_closeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel btn_close;
    private javax.swing.JLabel btn_login;
    private javax.swing.JLabel btn_lupaPass;
    private javax.swing.JLabel iconEyeClose;
    private javax.swing.JLabel iconEyeOpen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
