/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainMenu;

import SubMenu.Popup.PopupGagal;
import SubMenu.Popup.PopupSukses;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.*;
import koneksi.Connect;

/**
 *
 * @author rayrayaray
 */
public class LoginRFID extends javax.swing.JFrame {

    /**
     * Creates new form LoginRFID
     */
    public LoginRFID() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        txt_rfid.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_exit = new utility.custom_panel.PanelRound();
        background = new javax.swing.JLabel();
        txt_rfid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_exit.setBackground(new Color(0,0,0,0)
        );
        btn_exit.setRoundBottomLeft(50);
        btn_exit.setRoundBottomRight(50);
        btn_exit.setRoundTopLeft(50);
        btn_exit.setRoundTopRight(50);
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btn_exitLayout = new javax.swing.GroupLayout(btn_exit);
        btn_exit.setLayout(btn_exitLayout);
        btn_exitLayout.setHorizontalGroup(
            btn_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        btn_exitLayout.setVerticalGroup(
            btn_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(783, 180, 30, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/PopUp/Login RFID.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        txt_rfid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_rfidKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_rfidKeyTyped(evt);
            }
        });
        getContentPane().add(txt_rfid, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, 120, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        this.dispose();
    }//GEN-LAST:event_btn_exitMouseClicked

    private void txt_rfidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rfidKeyTyped

    }//GEN-LAST:event_txt_rfidKeyTyped

    private void txt_rfidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rfidKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                String sql = "Select * from akun where scan_ktp = '" + txt_rfid.getText() + "'";
                Connection conn = Connect.GetConnection();

                PreparedStatement pst = conn.prepareStatement(sql);
                ResultSet res = pst.executeQuery();

                if (res.next()) {
                    this.dispose();
                    MenuUtama mu = new MenuUtama();
                    mu.getIdAkun(res.getString("id_akun"), res.getString("hak_akses"));
                    mu.setVisible(true);
                    mu.cekRole();
                    new PopupSukses("Berhasil Login<br>Selamat datang " + res.getString("nama"), "").setVisible(true);
                } else {
                    txt_rfid.setText("");
                    txt_rfid.requestFocus();
                    new PopupGagal("Data Tidak Ditemukan<br>Silahkan Scan Kembali").setVisible(true);
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
                new PopupGagal("Data Tidak Ditemukan<br>Silahkan Scan Kembali").setVisible(true);
            }
        }
    }//GEN-LAST:event_txt_rfidKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginRFID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginRFID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginRFID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginRFID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginRFID().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private utility.custom_panel.PanelRound btn_exit;
    private javax.swing.JTextField txt_rfid;
    // End of variables declaration//GEN-END:variables
}
