/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainMenu;

import SubMenu.LaporanFrame;
import SubMenu.*;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.Timer;
import java.sql.*;
import koneksi.Connect;

/**
 *
 * @author rayrayaray
 */
public class MenuUtama extends javax.swing.JFrame {

    Color activeColor = new Color(0, 132, 161);
    Color nonActiveColor = new Color(0, 0, 0, 0);
    Color activeColorLogout = new Color(1, 177, 214);
    String hakAkses = "";

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {

        initComponents();
        tampilJam(lbl_jam);
        tampilTanggal(lbl_tanggal);

        titleMenu.setText("Dashboard");

        Transaksi.setBackground(nonActiveColor);
        Pelanggan.setBackground(nonActiveColor);
        DataPaket.setBackground(nonActiveColor);
        Laporan.setBackground(nonActiveColor);
        Karyawan.setBackground(nonActiveColor);
        Logout.setBackground(nonActiveColor);
        DashboardFrame df = new DashboardFrame();
        jDesktopPane1.add(df);

        df.setVisible(true);
    }

    public void cekRole() {
        if (hakAkses.equals("Karyawan")) {
            DataPaket.setVisible(false);
            Laporan.setVisible(false);
            Karyawan.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleMenu = new javax.swing.JLabel();
        titleAkun = new javax.swing.JLabel();
        titleRoleAkun = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        MenuBar = new javax.swing.JPanel();
        Dashboard = new utility.custom_panel.PanelRound();
        icon_dashboard = new javax.swing.JLabel();
        btn_dashboard = new javax.swing.JLabel();
        Transaksi = new utility.custom_panel.PanelRound();
        icon_transaksi = new javax.swing.JLabel();
        btn_transaksi = new javax.swing.JLabel();
        Pelanggan = new utility.custom_panel.PanelRound();
        icon_pelanggan = new javax.swing.JLabel();
        btn_pelanggan = new javax.swing.JLabel();
        DataPaket = new utility.custom_panel.PanelRound();
        icon_dataPaket = new javax.swing.JLabel();
        btn_dataPaket = new javax.swing.JLabel();
        Laporan = new utility.custom_panel.PanelRound();
        icon_laporan = new javax.swing.JLabel();
        btn_laporan = new javax.swing.JLabel();
        Karyawan = new utility.custom_panel.PanelRound();
        icon_karyawan = new javax.swing.JLabel();
        btn_karyawan = new javax.swing.JLabel();
        Logout = new utility.custom_panel.PanelRound();
        icon_keluar = new javax.swing.JLabel();
        btn_keluar = new javax.swing.JLabel();
        lbl_jam = new javax.swing.JLabel();
        lbl_tanggal = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        lbl_idAkun = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleMenu.setFont(new java.awt.Font("Poppins", 1, 50)); // NOI18N
        titleMenu.setForeground(new java.awt.Color(1, 176, 213));
        titleMenu.setText("TITLE HERE");
        getContentPane().add(titleMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 40, 490, 90));

        titleAkun.setFont(new java.awt.Font("Poppins", 1, 26)); // NOI18N
        titleAkun.setForeground(new java.awt.Color(1, 176, 213));
        titleAkun.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        titleAkun.setText("Akun");
        getContentPane().add(titleAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 45, 390, 50));

        titleRoleAkun.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        titleRoleAkun.setForeground(new java.awt.Color(1, 176, 213));
        titleRoleAkun.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        titleRoleAkun.setText("Akun");
        getContentPane().add(titleRoleAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 86, 390, 20));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 1100, 630));

        MenuBar.setOpaque(false);
        MenuBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Dashboard.setBackground(new java.awt.Color(0, 132, 161));
        Dashboard.setRoundBottomRight(60);
        Dashboard.setRoundTopRight(60);
        Dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashboardMouseClicked(evt);
            }
        });
        Dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/icon/dashboard.png"))); // NOI18N
        Dashboard.add(icon_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 60));

        btn_dashboard.setFont(new java.awt.Font("Poppins", 1, 22)); // NOI18N
        btn_dashboard.setForeground(new java.awt.Color(255, 255, 255));
        btn_dashboard.setText("Dashboard");
        btn_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseExited(evt);
            }
        });
        Dashboard.add(btn_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 150, 50));

        MenuBar.add(Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 247, -1));

        Transaksi.setBackground(new java.awt.Color(0, 132, 161));
        Transaksi.setRoundBottomRight(60);
        Transaksi.setRoundTopRight(60);
        Transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TransaksiMouseClicked(evt);
            }
        });
        Transaksi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/icon/transaksi.png"))); // NOI18N
        Transaksi.add(icon_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 60));

        btn_transaksi.setFont(new java.awt.Font("Poppins", 1, 22)); // NOI18N
        btn_transaksi.setForeground(new java.awt.Color(255, 255, 255));
        btn_transaksi.setText("Transaksi");
        btn_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_transaksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_transaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_transaksiMouseExited(evt);
            }
        });
        Transaksi.add(btn_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 150, 50));

        MenuBar.add(Transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 66, 247, -1));

        Pelanggan.setBackground(new java.awt.Color(0, 132, 161));
        Pelanggan.setRoundBottomRight(60);
        Pelanggan.setRoundTopRight(60);
        Pelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PelangganMouseClicked(evt);
            }
        });
        Pelanggan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_pelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/icon/pelanggan.png"))); // NOI18N
        Pelanggan.add(icon_pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 60));

        btn_pelanggan.setFont(new java.awt.Font("Poppins", 1, 22)); // NOI18N
        btn_pelanggan.setForeground(new java.awt.Color(255, 255, 255));
        btn_pelanggan.setText("Pelanggan");
        btn_pelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pelangganMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pelangganMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pelangganMouseExited(evt);
            }
        });
        Pelanggan.add(btn_pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 150, 50));

        MenuBar.add(Pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 132, 247, -1));

        DataPaket.setBackground(new java.awt.Color(0, 132, 161));
        DataPaket.setRoundBottomRight(60);
        DataPaket.setRoundTopRight(60);
        DataPaket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DataPaketMouseClicked(evt);
            }
        });
        DataPaket.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_dataPaket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/icon/data paket.png"))); // NOI18N
        DataPaket.add(icon_dataPaket, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 60));

        btn_dataPaket.setFont(new java.awt.Font("Poppins", 1, 22)); // NOI18N
        btn_dataPaket.setForeground(new java.awt.Color(255, 255, 255));
        btn_dataPaket.setText("Data Paket");
        btn_dataPaket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dataPaketMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dataPaketMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dataPaketMouseExited(evt);
            }
        });
        DataPaket.add(btn_dataPaket, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 150, 50));

        MenuBar.add(DataPaket, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 198, 247, -1));

        Laporan.setBackground(new java.awt.Color(0, 132, 161));
        Laporan.setRoundBottomRight(60);
        Laporan.setRoundTopRight(60);
        Laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LaporanMouseClicked(evt);
            }
        });
        Laporan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/icon/laporan.png"))); // NOI18N
        Laporan.add(icon_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 60));

        btn_laporan.setFont(new java.awt.Font("Poppins", 1, 22)); // NOI18N
        btn_laporan.setForeground(new java.awt.Color(255, 255, 255));
        btn_laporan.setText("Laporan");
        btn_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_laporanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_laporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_laporanMouseExited(evt);
            }
        });
        Laporan.add(btn_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 150, 50));

        MenuBar.add(Laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 264, 247, -1));

        Karyawan.setBackground(new java.awt.Color(0, 132, 161));
        Karyawan.setRoundBottomRight(60);
        Karyawan.setRoundTopRight(60);
        Karyawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KaryawanMouseClicked(evt);
            }
        });
        Karyawan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_karyawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/icon/karyawan.png"))); // NOI18N
        Karyawan.add(icon_karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 60));

        btn_karyawan.setFont(new java.awt.Font("Poppins", 1, 22)); // NOI18N
        btn_karyawan.setForeground(new java.awt.Color(255, 255, 255));
        btn_karyawan.setText("Akun");
        btn_karyawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_karyawanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_karyawanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_karyawanMouseExited(evt);
            }
        });
        Karyawan.add(btn_karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 150, 50));

        MenuBar.add(Karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 247, -1));

        Logout.setBackground(new java.awt.Color(1, 177, 214));
        Logout.setRoundBottomRight(60);
        Logout.setRoundTopRight(60);
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        Logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_keluar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/icon/logout.png"))); // NOI18N
        Logout.add(icon_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 60));

        btn_keluar.setFont(new java.awt.Font("Poppins", 1, 22)); // NOI18N
        btn_keluar.setForeground(new java.awt.Color(255, 255, 255));
        btn_keluar.setText("Logout");
        btn_keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_keluarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_keluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_keluarMouseExited(evt);
            }
        });
        Logout.add(btn_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 150, 50));

        MenuBar.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 456, 247, 61));

        getContentPane().add(MenuBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 250, 570));

        lbl_jam.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        lbl_jam.setForeground(new java.awt.Color(1, 176, 213));
        lbl_jam.setText("jam");
        getContentPane().add(lbl_jam, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 0, 100, 50));

        lbl_tanggal.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        lbl_tanggal.setForeground(new java.awt.Color(1, 176, 213));
        lbl_tanggal.setText("jam");
        getContentPane().add(lbl_tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, 180, 50));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/layout/Template Admin.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 770));

        lbl_idAkun.setText("jLabel1");
        getContentPane().add(lbl_idAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 60, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tampilJam(JLabel jlabel) {
        ActionListener taskPerformer = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                String nol_jam = "", nol_menit = "", nol_detik = "";

                java.util.Date dateTime = new java.util.Date();
                int nilai_jam = dateTime.getHours();
                int nilai_menit = dateTime.getMinutes();
                int nilai_detik = dateTime.getSeconds();

                if (nilai_jam <= 9) {
                    nol_jam = "0";
                }
                if (nilai_menit <= 9) {
                    nol_menit = "0";
                }
                if (nilai_detik <= 9) {
                    nol_detik = "0";
                }

                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);

                jlabel.setText(jam + ":" + menit + ":" + detik + "");
            }
        };
        new Timer(1000, taskPerformer).start();
    }

    public void tampilTanggal(JLabel label) {
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yyyy");
        label.setText(sdf.format(date));
    }

    public void getIdAkun(String id, String hakAkses) {
        lbl_idAkun.setText(id);
        this.hakAkses = hakAkses;

        try {
            Connection con = Connect.GetConnection();
            PreparedStatement pst = con.prepareStatement("Select * from akun where id_akun = '" + id + "'");
            ResultSet res = pst.executeQuery();
            if (res.next()) {
                titleAkun.setText(res.getString("nama"));
                titleRoleAkun.setText(res.getString("hak_akses"));
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    private void setHoverMenu() {
        if (titleMenu.getText().equals("Dashboard")) {
            Dashboard.setBackground(activeColor);
            Transaksi.setBackground(nonActiveColor);
            Pelanggan.setBackground(nonActiveColor);
            DataPaket.setBackground(nonActiveColor);
            Laporan.setBackground(nonActiveColor);
            Karyawan.setBackground(nonActiveColor);
            Logout.setBackground(nonActiveColor);
        } else if (titleMenu.getText().equals("Transaksi")) {
            Dashboard.setBackground(nonActiveColor);
            Transaksi.setBackground(activeColor);
            Pelanggan.setBackground(nonActiveColor);
            DataPaket.setBackground(nonActiveColor);
            Laporan.setBackground(nonActiveColor);
            Karyawan.setBackground(nonActiveColor);
            Logout.setBackground(nonActiveColor);
        } else if (titleMenu.getText().equals("Pelanggan")) {
            Dashboard.setBackground(nonActiveColor);
            Transaksi.setBackground(nonActiveColor);
            Pelanggan.setBackground(activeColor);
            DataPaket.setBackground(nonActiveColor);
            Laporan.setBackground(nonActiveColor);
            Karyawan.setBackground(nonActiveColor);
            Logout.setBackground(nonActiveColor);
        } else if (titleMenu.getText().equals("Data Paket")) {
            Dashboard.setBackground(nonActiveColor);
            Transaksi.setBackground(nonActiveColor);
            Pelanggan.setBackground(nonActiveColor);
            DataPaket.setBackground(activeColor);
            Laporan.setBackground(nonActiveColor);
            Karyawan.setBackground(nonActiveColor);
            Logout.setBackground(nonActiveColor);
        } else if (titleMenu.getText().equals("Laporan")) {
            Dashboard.setBackground(nonActiveColor);
            Transaksi.setBackground(nonActiveColor);
            Pelanggan.setBackground(nonActiveColor);
            DataPaket.setBackground(nonActiveColor);
            Laporan.setBackground(activeColor);
            Karyawan.setBackground(nonActiveColor);
            Logout.setBackground(nonActiveColor);
        } else if (titleMenu.getText().equals("Akun")) {
            Dashboard.setBackground(nonActiveColor);
            Transaksi.setBackground(nonActiveColor);
            Pelanggan.setBackground(nonActiveColor);
            DataPaket.setBackground(nonActiveColor);
            Laporan.setBackground(nonActiveColor);
            Karyawan.setBackground(activeColor);
            Logout.setBackground(nonActiveColor);
        } else if (titleMenu.getText().length() != 0) {
            Dashboard.setBackground(nonActiveColor);
            Transaksi.setBackground(nonActiveColor);
            Pelanggan.setBackground(nonActiveColor);
            DataPaket.setBackground(nonActiveColor);
            Laporan.setBackground(nonActiveColor);
            Karyawan.setBackground(nonActiveColor);
            Logout.setBackground(nonActiveColor);
        }
    }

    private void DashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardMouseClicked
        titleMenu.setText("Dashboard");

        Dashboard.setBackground(activeColor);
        Transaksi.setBackground(nonActiveColor);
        Pelanggan.setBackground(nonActiveColor);
        DataPaket.setBackground(nonActiveColor);
        Laporan.setBackground(nonActiveColor);
        Karyawan.setBackground(nonActiveColor);

        //tutup internalFrame yang lain
        jDesktopPane1.removeAll();

        //buka internalFrame
        DashboardFrame df = new DashboardFrame();
        jDesktopPane1.add(df);
        df.setVisible(true);

    }//GEN-LAST:event_DashboardMouseClicked

    private void btn_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseClicked
        titleMenu.setText("Dashboard");

        Dashboard.setBackground(activeColor);
        Transaksi.setBackground(nonActiveColor);
        Pelanggan.setBackground(nonActiveColor);
        DataPaket.setBackground(nonActiveColor);
        Laporan.setBackground(nonActiveColor);
        Karyawan.setBackground(nonActiveColor);

        //tutup internalFrame yang lain
        jDesktopPane1.removeAll();

        //buka internalFrame
        DashboardFrame df = new DashboardFrame();
        jDesktopPane1.add(df);
        df.setVisible(true);
    }//GEN-LAST:event_btn_dashboardMouseClicked

    private void TransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransaksiMouseClicked
        titleMenu.setText("Transaksi");

        Dashboard.setBackground(nonActiveColor);
        Transaksi.setBackground(activeColor);
        Pelanggan.setBackground(nonActiveColor);
        DataPaket.setBackground(nonActiveColor);
        Laporan.setBackground(nonActiveColor);
        Karyawan.setBackground(nonActiveColor);

        //tutup internalFrame yang lain
        jDesktopPane1.removeAll();

        //buka internalFrame
        TransaksiFrame tf = new TransaksiFrame();
        jDesktopPane1.add(tf);
        tf.setIdAkun(lbl_idAkun.getText());
        tf.setVisible(true);
    }//GEN-LAST:event_TransaksiMouseClicked

    private void btn_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_transaksiMouseClicked
        titleMenu.setText("Transaksi");

        Dashboard.setBackground(nonActiveColor);
        Transaksi.setBackground(activeColor);
        Pelanggan.setBackground(nonActiveColor);
        DataPaket.setBackground(nonActiveColor);
        Laporan.setBackground(nonActiveColor);
        Karyawan.setBackground(nonActiveColor);

        //tutup internalFrame yang lain
        jDesktopPane1.removeAll();

        //buka internalFrame
        TransaksiFrame tf = new TransaksiFrame();
        jDesktopPane1.add(tf);
        tf.setIdAkun(lbl_idAkun.getText());
        tf.setVisible(true);
    }//GEN-LAST:event_btn_transaksiMouseClicked

    private void PelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PelangganMouseClicked
        titleMenu.setText("Pelanggan");

        Dashboard.setBackground(nonActiveColor);
        Transaksi.setBackground(nonActiveColor);
        Pelanggan.setBackground(activeColor);
        DataPaket.setBackground(nonActiveColor);
        Laporan.setBackground(nonActiveColor);
        Karyawan.setBackground(nonActiveColor);

        //tutup internalFrame yang lain
        jDesktopPane1.removeAll();

        //buka internalFrame
        PelangganFrame pf = new PelangganFrame();
        jDesktopPane1.add(pf);
        pf.setVisible(true);
    }//GEN-LAST:event_PelangganMouseClicked

    private void btn_pelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pelangganMouseClicked
        titleMenu.setText("Pelanggan");

        Dashboard.setBackground(nonActiveColor);
        Transaksi.setBackground(nonActiveColor);
        Pelanggan.setBackground(activeColor);
        DataPaket.setBackground(nonActiveColor);
        Laporan.setBackground(nonActiveColor);
        Karyawan.setBackground(nonActiveColor);

        //tutup internalFrame yang lain
        jDesktopPane1.removeAll();

        //buka internalFrame
        PelangganFrame pf = new PelangganFrame();
        jDesktopPane1.add(pf);
        pf.setVisible(true);
    }//GEN-LAST:event_btn_pelangganMouseClicked

    private void DataPaketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataPaketMouseClicked
        titleMenu.setText("Data Paket");

        Dashboard.setBackground(nonActiveColor);
        Transaksi.setBackground(nonActiveColor);
        Pelanggan.setBackground(nonActiveColor);
        DataPaket.setBackground(activeColor);
        Laporan.setBackground(nonActiveColor);
        Karyawan.setBackground(nonActiveColor);

        //tutup internalFrame yang lain
        jDesktopPane1.removeAll();

        //buka internalFrame
        DataPaketFrame dpf = new DataPaketFrame();
        jDesktopPane1.add(dpf);
        dpf.setVisible(true);
    }//GEN-LAST:event_DataPaketMouseClicked

    private void btn_dataPaketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dataPaketMouseClicked
        titleMenu.setText("Data Paket");

        Dashboard.setBackground(nonActiveColor);
        Transaksi.setBackground(nonActiveColor);
        Pelanggan.setBackground(nonActiveColor);
        DataPaket.setBackground(activeColor);
        Laporan.setBackground(nonActiveColor);
        Karyawan.setBackground(nonActiveColor);

        //tutup internalFrame yang lain
        jDesktopPane1.removeAll();

        //buka internalFrame
        DataPaketFrame dpf = new DataPaketFrame();
        jDesktopPane1.add(dpf);
        dpf.setVisible(true);
    }//GEN-LAST:event_btn_dataPaketMouseClicked

    private void LaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LaporanMouseClicked
        titleMenu.setText("Laporan");

        Dashboard.setBackground(nonActiveColor);
        Transaksi.setBackground(nonActiveColor);
        Pelanggan.setBackground(nonActiveColor);
        DataPaket.setBackground(nonActiveColor);
        Laporan.setBackground(activeColor);
        Karyawan.setBackground(nonActiveColor);

        //tutup internalFrame yang lain
        jDesktopPane1.removeAll();

        //buka internalFrame
        LaporanFrame lf = new LaporanFrame();
        jDesktopPane1.add(lf);
        lf.setVisible(true);
    }//GEN-LAST:event_LaporanMouseClicked

    private void btn_laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_laporanMouseClicked
        titleMenu.setText("Laporan");

        Dashboard.setBackground(nonActiveColor);
        Transaksi.setBackground(nonActiveColor);
        Pelanggan.setBackground(nonActiveColor);
        DataPaket.setBackground(nonActiveColor);
        Laporan.setBackground(activeColor);
        Karyawan.setBackground(nonActiveColor);

        //tutup internalFrame yang lain
        jDesktopPane1.removeAll();

        //buka internalFrame
        LaporanFrame lf = new LaporanFrame();
        jDesktopPane1.add(lf);
        lf.setVisible(true);
    }//GEN-LAST:event_btn_laporanMouseClicked

    private void KaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KaryawanMouseClicked
        titleMenu.setText("Akun");

        Dashboard.setBackground(nonActiveColor);
        Transaksi.setBackground(nonActiveColor);
        Pelanggan.setBackground(nonActiveColor);
        DataPaket.setBackground(nonActiveColor);
        Laporan.setBackground(nonActiveColor);
        Karyawan.setBackground(activeColor);

        //tutup internalFrame yang lain
        jDesktopPane1.removeAll();

        //buka internalFrame
        KaryawanFrame kf = new KaryawanFrame();
        jDesktopPane1.add(kf);
        kf.setVisible(true);
    }//GEN-LAST:event_KaryawanMouseClicked

    private void btn_karyawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_karyawanMouseClicked
        titleMenu.setText("Akun");

        Dashboard.setBackground(nonActiveColor);
        Transaksi.setBackground(nonActiveColor);
        Pelanggan.setBackground(nonActiveColor);
        DataPaket.setBackground(nonActiveColor);
        Laporan.setBackground(nonActiveColor);
        Karyawan.setBackground(activeColor);

        //tutup internalFrame yang lain
        jDesktopPane1.removeAll();

        //buka internalFrame
        KaryawanFrame kf = new KaryawanFrame();
        jDesktopPane1.add(kf);
        kf.setVisible(true);
    }//GEN-LAST:event_btn_karyawanMouseClicked

    private void btn_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseEntered
        Dashboard.setBackground(activeColor);
    }//GEN-LAST:event_btn_dashboardMouseEntered

    private void btn_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseExited
        setHoverMenu();
    }//GEN-LAST:event_btn_dashboardMouseExited

    private void btn_transaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_transaksiMouseEntered
        Transaksi.setBackground(activeColor);
    }//GEN-LAST:event_btn_transaksiMouseEntered

    private void btn_transaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_transaksiMouseExited
        setHoverMenu();
    }//GEN-LAST:event_btn_transaksiMouseExited

    private void btn_pelangganMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pelangganMouseEntered
        Pelanggan.setBackground(activeColor);
    }//GEN-LAST:event_btn_pelangganMouseEntered

    private void btn_pelangganMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pelangganMouseExited
        setHoverMenu();
    }//GEN-LAST:event_btn_pelangganMouseExited

    private void btn_dataPaketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dataPaketMouseEntered
        DataPaket.setBackground(activeColor);
    }//GEN-LAST:event_btn_dataPaketMouseEntered

    private void btn_dataPaketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dataPaketMouseExited
        setHoverMenu();
    }//GEN-LAST:event_btn_dataPaketMouseExited

    private void btn_laporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_laporanMouseEntered
        Laporan.setBackground(activeColor);
    }//GEN-LAST:event_btn_laporanMouseEntered

    private void btn_laporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_laporanMouseExited
        setHoverMenu();
    }//GEN-LAST:event_btn_laporanMouseExited

    private void btn_karyawanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_karyawanMouseEntered
        Karyawan.setBackground(activeColor);
    }//GEN-LAST:event_btn_karyawanMouseEntered

    private void btn_karyawanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_karyawanMouseExited
        setHoverMenu();
    }//GEN-LAST:event_btn_karyawanMouseExited

    private void btn_keluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_keluarMouseEntered
        Logout.setBackground(activeColorLogout);
    }//GEN-LAST:event_btn_keluarMouseEntered

    private void btn_keluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_keluarMouseExited
        setHoverMenu();
    }//GEN-LAST:event_btn_keluarMouseExited

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        new KonfirmasiLogout("Apakah yakin ingin keluar?", this).setVisible(true);
    }//GEN-LAST:event_LogoutMouseClicked

    private void btn_keluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_keluarMouseClicked
        new KonfirmasiLogout("Apakah yakin ingin keluar?", this).setVisible(true);
    }//GEN-LAST:event_btn_keluarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utility.custom_panel.PanelRound Dashboard;
    private utility.custom_panel.PanelRound DataPaket;
    private utility.custom_panel.PanelRound Karyawan;
    private utility.custom_panel.PanelRound Laporan;
    private utility.custom_panel.PanelRound Logout;
    private javax.swing.JPanel MenuBar;
    private utility.custom_panel.PanelRound Pelanggan;
    private utility.custom_panel.PanelRound Transaksi;
    private javax.swing.JLabel background;
    private javax.swing.JLabel btn_dashboard;
    private javax.swing.JLabel btn_dataPaket;
    private javax.swing.JLabel btn_karyawan;
    private javax.swing.JLabel btn_keluar;
    private javax.swing.JLabel btn_laporan;
    private javax.swing.JLabel btn_pelanggan;
    private javax.swing.JLabel btn_transaksi;
    private javax.swing.JLabel icon_dashboard;
    private javax.swing.JLabel icon_dataPaket;
    private javax.swing.JLabel icon_karyawan;
    private javax.swing.JLabel icon_keluar;
    private javax.swing.JLabel icon_laporan;
    private javax.swing.JLabel icon_pelanggan;
    private javax.swing.JLabel icon_transaksi;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel lbl_idAkun;
    private javax.swing.JLabel lbl_jam;
    private javax.swing.JLabel lbl_tanggal;
    private javax.swing.JLabel titleAkun;
    private javax.swing.JLabel titleMenu;
    private javax.swing.JLabel titleRoleAkun;
    // End of variables declaration//GEN-END:variables

}
